//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int ChildId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string ChildName { get; set; }
        public string ChildTz { get; set; }
        public Nullable<System.DateTime> ChildBornDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
